### PR TITLE
login/signUp module

### PR DESCRIPTION
**Pull request by gugakatsi**
Sorry that i pushed it to directly master branch , so about push , as you can see i decoupled login/signup module , and moved it to independent package as i mentioned we'll package by features ,  i also made data package and there will be models and all bussiness logic, interactors  . and also in LoginPresenter , ok_login and ok_signup takes handler as a argument which lead us to import android library in presenter which is not good practice i know , but as well as i am gonna refactor project to retrofit/rxJava it really doesn't matter now , first i am gonna decouple and refactor every module to mvp and than it will be much easier to move to retrofit/rxjava.

### CODE REVIEW

**Comment by Swati4star** [comment]
Shouldn't we move to retrofit also side by side?

**Comment by gugakatsi** [comment]
@Swati4star i think it will be huge pain  as i said , first let's finish modules and than it will be pretty easy to refactor  i guess .

**Comment by Swati4star** [comment]
Cool then, will merge it soon!

You can work on other modules too by then.

**Comment by Swati4star** [comment]
@gugakatsi Can you resolve the merge conflicts? Also, Are you working on cleaning up other modules?

**Comment by gugakatsi** [comment]
@Swati4star i'll fix it tonight , in few hrs in my country so :D

**Comment by gugakatsi** [comment]
and yes i am working on other modules to.

**Comment by gugakatsi** [comment]
guess i fix that,  test probably failed because of some license agrements , @Swati4star  , and sorry again for somehow pushing on master branch directly , have not been around for a long time already. good to be back.

**Comment by gugakatsi** [comment]
now i moved to AddNewTrip module

**Comment by gugakatsi** [comment]
@Swati4star fixed travis too.

**Comment by Swati4star** [comment]
@gugakatsi Will be merging it after https://github.com/Swati4star/Travel-Mate/issues/24 is resolved.

**Comment by Swati4star** [comment]
This can be closed, as the changes are already incorporated in https://github.com/Swati4star/Travel-Mate/pull/38

**Pull request closed without merging**
